### ISSUE TITLE
How do I add custom plugins ?

### ISSUE THREAD

**Issue by AnimeshRy** [amplication/plugins#101]
I've been using amplification for a side project, the auth done in the project is by keycloak. That is why I had to seperate out since there's oauth based auth in the current list of plugins.

Are you guys accepting contributions here ?, I can probably come up with a way for keycloak to run as a plugin similar to what I did for my use case depending on how plugins work with amplication.

Also there are a few documentation errors in this repo like [this](https://github.com/amplication/plugins/blob/master/plugins/auth-jwt/README.md#:~:text=This%20plugin%20is-,integrarted,-with%20the%20default).

**Comment by souravjain540** [comment]
You are more than welcome to contribute to this repositories.

Can you open specific issues and then our team will discuss on each issue separate.

I will make sure that you get all the support you need.

Maybe for a new plugin, if accepted, we can open a private discord channel for discussion.

**Comment by overbit** [comment]
Closing this as KeyCloak plugin is now released
