### ISSUE TITLE
As a dev I would like to create a plugin based on Cloudinary

### ISSUE THREAD

**Issue by roopeshsn** [amplication/plugins#118]
Cloudinary enables users to manage and optimize images. It will be a great addition to the Amplication plugin system. And, I would like to work on this!

**Comment by mulygottlieb** [comment]
Hi @roopeshsn 
Sorry for the very delayed response. We are not tracking issues on this repo but only on our main repo amplication/amplication.

We are always happy to receive community plugins.
Can you write some elaboration on what you see this plugin doing? I mean to describe a bit more what it will add to the generated services, and what this will allow to do with Cloudinary?

Please @ tag me when you respond so I don't miss it. You are also welcome to join our [Discord](https://amplication.com/discord) server where you can interact with other contributors as well as core team members about your ideas, and to get help and assistance.
