### ISSUE TITLE
🐛 Bug Report: Kafka plugin is broken

### ISSUE THREAD

**Issue by arielweinberger** [amplication/plugins#14]
# What happened

## 1. Mismatching `@nestjs/microservices` version
The plugin installs `@nestjs/microservices` at `^8.3.0` (notice the caret). The rest of the NestJS packages are pinned to version 8.3.0.

As a result, the actual version installed does not match with NestJS. This results in a TypeError as soon as you run the generated service.

## 2. Topics enum not exported
We need to add `export ` to the topic names enum, otherwise they are pointless and not usable.

## 3. Package.json in the plugin uses a different major version
In the plugin source code, in `package.json`, we currently install `@nestjs/microservices` at version 9 (I assume this is for access to types). We need to pin this down to `8.3.0` as well, otherwise we will, again, face mismatching types and cause errors.

______

Make sure to publish a new NPM version and update the DSG.

**Test and make sure this works.**

**Comment by abrl91** [comment]
@GreenMachine01 
Ofek fixed the versions issue, and I see that the service's topic is generated with `export`


![Image](https://user-images.githubusercontent.com/39680385/196897756-4d9f3dbb-aa97-4a53-b374-425adbd286a0.png)

So, it seems that this issue was resolved
