### ISSUE TITLE
Bug Report: Failed to execute plugin event: CreateServerDotEnv. Error message: {} with MongoDB plugin

### ISSUE THREAD

**Issue by TheUndex** [amplication/plugins#83]
When committing & building with MongoDB version 1.2.6 installed it gives the following error:
`(Error) failed to execute plugin event: CreateServerDotEnv. Error message: {}` - No .env file is being created 

With 1.2.4, everything works as expected.

![Screenshot 2023-03-21 144030](https://user-images.githubusercontent.com/45672896/226703066-2b371bea-d9d3-4945-9f44-18febd5b21ed.png)
![Screenshot 2023-03-21 144156](https://user-images.githubusercontent.com/45672896/226703089-4feefd27-1662-4c7d-b3c4-255745200287.png)

**Comment by levivannoort** [comment]
@tupe12334 do you know if this issue has since been circumvented/solved?

**Comment by tupe12334** [comment]
Yes, https://github.com/amplication/plugins/pull/85
